### PR TITLE
Fixing Download Bugs

### LINKED ISSUE #598: needs try catch to handle error
https://github.com/dali-lab/pine-beetle-frontend/blob/704b1969cd643db680ff95afd8225f7eaadf2680/src/components/download-data/component.js#L65-L90

### LINKED ISSUE #599: Download data not working for unsummarized
# Description

https://pine-beetle-automation.herokuapp.com/v3undefined?state=TX&startYear=2000&endYear=2022

it creates this 'undefined' instead of /unsummarized-trapping/download

Look here: https://github.com/dali-lab/pine-beetle-frontend/blob/dev/src/utils/network.js#L30-L55
and here: https://github.com/dali-lab/pine-beetle-frontend/blob/dev/src/constants/index.js#L80-L86

there lies an error, please fix.

connects with #598 

## Type of Issue

- [ ] New feature
- [x] Bug fix
- [ ] Documentation update

### PR DESCRIPTION
**Pull request by shreyaj1212**
# Description

Fixing bugs related to downloading data. 

## Type of Change

- [ ] New feature
- [x] Bug fix
- [ ] Breaking change
- [ ] Documentation update

## Checklist

- [ ] Unit/integration tests
- [ ] Documentation

## Tickets

- closes #599 
- closes #598 

Please attach any design screenshots if UI update.

### CODE REVIEW

File: src/components/download-data/component.js [hunk 1]
```diff
@@ -63,29 +65,38 @@ const DownloadData = (props) => {
...
+          ? `${fieldName}_${dataTypeName}`
+          : fieldName;
+
+        // to allow multiple counties/RD
+        const countyString = county.join('&county=');
+        const rangerDistrictString = rangerDistrict.join('&rangerDistrict=');
+
+        return downloadCsv(dataName, {
+          state: selectedState,
+          // [countyMode ? 'county' : 'rangerDistrict']: countyMode ? county : rangerDistrict,
```
Comment (jeffzyliu) [inline src/components/download-data/component.js]: this can be deleted

**Review by jeffzyliu — APPROVED** [review]
cool looks good!
